services:
  db:
    image: mysql:latest
    container_name: mysql-board
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: board
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: